# Nach .github/workflows/dependabot-automerge.yml kopieren.

name: Dependabot Auto-Merge

on: pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  automerge:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    uses: kvnflx/github/.github/workflows/dependabot-automerge.yml@v1
    secrets:
      AUTOMERGE_CLIENT_ID: ${{ secrets.AUTOMERGE_CLIENT_ID }}
      AUTOMERGE_APP_KEY: ${{ secrets.AUTOMERGE_APP_KEY }}
      NTFY_URL: ${{ secrets.NTFY_URL }}
